💄 Add icon for matters and ipfs in post column
likecoin/likecoin-wordpress pull request #102
Opened 2021-03-04 14:26 UTC by williamchong

![image](https://user-images.githubusercontent.com/6198816/109978225-a1bb9d80-7d38-11eb-8217-f31211cda8ec.png)

2021-03-04 18:42 UTC, shellyYG approved these changes

2021-03-08 06:46 UTC, nwingt requested changes

2021-03-08 06:46 UTC, nwingt commented on likecoin/assets/icon/matters.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><defs><style>.cls-1{fill:none;stroke:#444;}.cls-2{fill:#444;fill-rule:evenodd;}</style></defs><path class=
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M19.5,10a5.84,5.84,0,1,1-5.86-5.82h0A5.83,5.83,0,0,1,19.5,10Z" fill="none" stroke="#444"/><path d="M6.83,16.81A6.81,6.81,0,1,0,0,10a6.81,6.81,0,0,0,6.83,6.81Z" fill="#444" fill-rule="evenodd"/></svg>
```

2021-03-08 06:46 UTC, nwingt commented on likecoin/assets/icon/ipfs.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><defs><style>.cls-1{fill:none;stroke:#444;stroke-miterlimit:10;stroke-width:1.5px;}.cls-2{fill:#444;}</sty
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><g fill="#444"><path d="M12.6,2.5A3,3,0,0,1,8.5,3.6,2.91,2.91,0,0,1,7.4,2.5L10,1Z"/><path d="M4.15,15.63a2.24,2.24,0,0,0-1.94-3.38V14.5Z"/><path d="M4.15,4.37A2.24,2.24,0,0,1,2.21,7.75V5.5Z"/><path d="M15.85,4.37a2.24,2.24,0,0,0,1.94,3.38h0V5.5Z"/><path d="M12,17.87a2.26,2.26,0,0,0-3.09-.81,2.33,2.33,0,0,0-.81.81L10,19Z"/><path d="M17.79,11.5a3,3,0,0,0-3,3A2.92,2.92,0,0,0,15.2,16l2.59-1.5Z"/><circle cx="10" cy="10" r="2"/></g><path d="M17.79,14.5v-9L10,1,2.21,5.5v9L10,19ZM2.21,5.5,10,10l7.79-4.5M10,10v9" fill="none" stroke="#444" stroke-miterlimit="10" stroke-width="1.5"/></svg>
```

2021-03-08 12:57 UTC, nwingt approved these changes

2021-03-08 13:23 UTC, merged