✨ Add publish/ipfs status and api functions
likecoin/likecoin-wordpress pull request #90
Opened 2020-12-16 18:27 UTC by williamchong

New info in metabox and post list columns

2020-12-17 02:51 UTC, nnkken approved these changes

2020-12-18 09:12 UTC, nwingt requested changes

2020-12-18 09:12 UTC, nwingt commented on likecoin/admin/views/components.php
> +					<abs
<abs?

2020-12-18 09:19 UTC, nwingt approved these changes

2020-12-21 02:11 UTC, nwingt approved these changes

2020-12-21 07:06 UTC, merged